//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public NhaCungCap()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string ThongTin { get; set; }
        public Nullable<System.DateTime> NgayHopTac { get; set; }
        public Nullable<bool> Xoa { get; set; }
    
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
