//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        public PhieuXuat()
        {
            this.ThongTinPhieuXuats = new HashSet<ThongTinPhieuXuat>();
        }
    
        public string Id { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
    
        public virtual ICollection<ThongTinPhieuXuat> ThongTinPhieuXuats { get; set; }
    }
}
