//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using QuanLyBanHang.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap:BaseViewModel
    {
        public NhaCungCap()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
        private int _Id;
        public int Id { get { return _Id; } set { _Id = value; OnPropertyChanged(); } }
        private string _Ten;
        public string Ten { get { return _Ten; } set { _Ten = value; OnPropertyChanged(); } }
        private string _DiaChi;
        public string DiaChi { get { return _DiaChi; } set { _DiaChi = value; OnPropertyChanged(); } }
        private string _DienThoai;
        public string DienThoai { get { return _DienThoai; } set { _DienThoai = value; OnPropertyChanged(); } }
        private string _Email;
        public string Email { get { return _Email; } set { _Email = value; OnPropertyChanged(); } }
        private string _ThongTin;
        public string ThongTin { get { return _ThongTin; } set { _ThongTin = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _NgayHopTac;
        public Nullable<System.DateTime> NgayHopTac { get { return _NgayHopTac; } set { _NgayHopTac = value; OnPropertyChanged(); } }
        public Nullable<bool> Xoa { get; set; }

        private ICollection<SanPham> _SanPhams;
        public virtual ICollection<SanPham> SanPhams { get { return _SanPhams; } set { _SanPhams = value; OnPropertyChanged(); } }
    }
}
