//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinPhieuXuat
    {
        public string Id { get; set; }
        public string IdSanPham { get; set; }
        public string IdPhieuXuat { get; set; }
        public int IdKhachHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
